feat: [AB#15816] create CDK resources

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -19,28 +19,61 @@ commands:
       - run:
           name: Install yarn packages
           command: yarn install
-  validate-serverless-access-key:
-    steps:
-      - run:
-          name: Validate Serverless Access Key
-          command: |
-            echo "Validating SERVERLESS_ACCESS_KEY"
-            if [ -z "${SERVERLESS_ACCESS_KEY}" ]; then
-              echo "Error: SERVERLESS_ACCESS_KEY is not set"
-              exit 1
-            else
-              echo "SERVERLESS_ACCESS_KEY is set"
-            fi
   install-dynamodb:
     steps:
       - run:
           name: Install Dynamodb local
           command: yarn workspace @businessnjgovnavigator/api install-dynamo-local
+  start-dynamodb:
+    steps:
+      - run:
+          name: Start DynamoDB
+          background: true
+          command: |
+            cd api
+            echo "Starting DynamoDB Local..."
+            java -Djava.library.path=.dynamodb/DynamoDBLocal_lib \
+                 -jar .dynamodb/DynamoDBLocal.jar \
+                 -sharedDb -port 8000 > dynamodb.log 2>&1
+  wait-for-dynamodb:
+    steps:
+      - run:
+          name: Wait for DynamoDB Local to be ready
+          command: |
+            echo "Waiting for DynamoDB Local to be ready..."
+            ATTEMPTS=0
+            until curl -s http://localhost:8000 >/dev/null; do
+              ATTEMPTS=$((ATTEMPTS+1))
+              if [ "$ATTEMPTS" -ge 20 ]; then
+                echo "DynamoDB did not start within expected time. Dumping logs:"
+                cat api/dynamodb.log || true
+                exit 1
+              fi
+              echo "DynamoDB not ready, retrying... ($ATTEMPTS)"
+              sleep 3
+            done
+            echo "DynamoDB Local is ready!"
+  initialize-dynamodb-tables:
+    steps:
+      - run:
+          name: Initialize DynamoDB Tables
+          command: |
+            echo "Creating tables..."
+            cd api
+            aws dynamodb create-table \
+              --cli-input-json file://users-dynamodb-schema.json \
+              --endpoint-url http://localhost:8000 \
+              --region us-east-1 || echo "users table already exists"
+
+            aws dynamodb create-table \
+              --cli-input-json file://businesses-dynamodb-schema.json \
+              --endpoint-url http://localhost:8000 \
+              --region us-east-1 || echo "businesses table already exists"
+            echo "Tables initialized!"
 
   configure:
     steps:
       - bootstrap-code
-      - validate-serverless-access-key
   configure-smoke-test:
     steps:
       - run: sudo apt update
@@ -180,13 +213,26 @@ commands:
             - ./web/.next/cache
             - ~/.npm-global
 
-  deploy-serverless:
+  deploy-cdk:
     steps:
       - run:
-          name: Deploy Serverless
-          command:
-            yarn workspace @businessnjgovnavigator/api serverless deploy --verbose --stage ${STAGE}
-            --region us-east-1
+          name: Clear CDK Context
+          command: |
+            yarn workspace @businessnjgovnavigator/api-cdk cdk context --clear
+      - run:
+          name: CDK Bootstrap
+          command: |
+            echo "Running CDK bootstrap for stage: $STAGE ..."
+            yarn workspace @businessnjgovnavigator/api-cdk cdk bootstrap aws://$AWS_ACCOUNT_ID/us-east-1 \
+              --bootstrap-bucket-name cdk-biz-nj-assets-$AWS_ACCOUNT_ID-us-east-1 \
+              --qualifier biz-nj \
+              --trust arn:aws:iam::$AWS_ACCOUNT_ID:user/system/bfs-navigator \
+              --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess || \
+              echo "Bootstrap already completed or not required."
+      - run:
+          name: Deploy CDK
+          command: |
+            yarn workspace @businessnjgovnavigator/api-cdk cdk deploy --all --qualifier biz-nj --verbose --region us-east-1 --require-approval never
 
   set-shared-stage-env-vars:
     steps:
@@ -199,6 +245,10 @@ commands:
       - run:
           name: Set Development Environment Variables
           command: |
+            echo 'export VPC_ID=$VPC_ID_AWS_DEV' >> $BASH_ENV
+            echo 'export SUBNET_ID_01=$SUBNET_ID_01_AWS_DEV' >> $BASH_ENV
+            echo 'export SUBNET_ID_02=$SUBNET_ID_02_AWS_DEV' >> $BASH_ENV
+            echo 'export SG_ID=$SG_ID_AWS_DEV' >> $BASH_ENV
             echo 'export AB_TESTING_EXPERIENCE_B_PERCENTAGE=$AB_TESTING_EXPERIENCE_B_PERCENTAGE_DEV' >> $BASH_ENV
             echo 'export ABC_ETP_API_ACCOUNT=$ABC_ETP_API_ACCOUNT_STAGING' >> $BASH_ENV
             echo 'export ABC_ETP_API_BASE_URL=$ABC_ETP_API_BASE_URL_STAGING' >> $BASH_ENV
@@ -218,7 +268,6 @@ commands:
             echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV' >> $BASH_ENV
             echo 'export BASIC_AUTH_PASSWORD=$BASIC_AUTH_PASSWORD' >> $BASH_ENV
             echo 'export BASIC_AUTH_USERNAME=$BASIC_AUTH_USERNAME' >> $BASH_ENV
-            echo 'export BIZNJ_SLS_DEPLOYMENT_BUCKET_NAME=$BIZNJ_SLS_DEPLOYMENT_BUCKET_NAME_DEV' >> $BASH_ENV
             echo 'export BUSINESS_NAME_BASE_URL=$BUSINESS_NAME_BASE_URL_DEV' >> $BASH_ENV
             echo 'export CHECK_DEAD_LINKS=$CHECK_DEAD_LINKS_DEV' >> $BASH_ENV
             echo 'export COGNITO_IDENTITY_POOL_ID=$COGNITO_IDENTITY_POOL_ID_DEV' >> $BASH_ENV
@@ -262,7 +311,6 @@ commands:
             echo 'export MYNJ_SERVICE_URL=$MYNJ_SERVICE_URL_DEV' >> $BASH_ENV
             echo 'export NEXT_PUBLIC_WEB_BASE_URL=$WEB_BASE_URL_DEV' >> $BASH_ENV
             echo 'export REDIRECT_URL=$REDIRECT_URL_DEV' >> $BASH_ENV
-            echo 'export SERVERLESS_ACCESS_KEY=$SERVERLESS_ACCESS_KEY_DEV' >> $BASH_ENV
             echo 'export SHOW_DISABLED_INDUSTRIES=$DEV_SHOW_DISABLED_INDUSTRIES' >> $BASH_ENV
             echo 'export SMOKE_TEST_ENV=$SMOKE_TEST_ENV_DEV' >> $BASH_ENV
             echo 'export TAX_CLEARANCE_CERTIFICATE_PASSWORD=$TAX_CLEARANCE_CERTIFICATE_PASSWORD_DEV' >> $BASH_ENV
@@ -276,8 +324,12 @@ commands:
       - run:
           name: Set Cypress Environment Variables
           command: |
-            echo 'export SERVERLESS_ACCESS_KEY=$SERVERLESS_ACCESS_KEY_DEV' >> $BASH_ENV
-            echo 'export API_BASE_URL=http://localhost:5002/local' >> $BASH_ENV
+            echo 'export AWS_REGION=us-east-1' >> $BASH_ENV
+            echo 'export IS_OFFLINE=true' >> $BASH_ENV
+            echo 'export STAGE=local' >> $BASH_ENV
+            echo 'export DYNAMODB_ENDPOINT=http://localhost:8000' >> $BASH_ENV
+            echo 'export DYNAMO_PORT=8000' >> $BASH_ENV
+            echo 'export API_BASE_URL=http://localhost:5002' >> $BASH_ENV
             echo 'export USE_FAKE_SELF_REG=true' >> $BASH_ENV
             echo 'export REDIRECT_URL=http://localhost:3000/' >> $BASH_ENV
             echo 'export COGNITO_WEB_CLIENT_ID=$COGNITO_WEB_CLIENT_ID_DEV' >> $BASH_ENV
@@ -285,14 +337,14 @@ commands:
             echo 'export USE_WIREMOCK_FOR_FORMATION_AND_BUSINESS_SEARCH=true' >> $BASH_ENV
 
             echo 'export ADMIN_PASSWORD=Test1!' >> $BASH_ENV
-            echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV' >> $BASH_ENV
+            echo 'export AWS_ACCESS_KEY_ID=local' >> $BASH_ENV
             echo 'export AWS_CRYPTO_CONTEXT_ORIGIN=$AWS_CRYPTO_CONTEXT_ORIGIN' >> $BASH_ENV
             echo 'export AWS_CRYPTO_CONTEXT_STAGE=$AWS_CRYPTO_CONTEXT_STAGE_DEV' >> $BASH_ENV
             echo 'export AWS_CRYPTO_CONTEXT_TAX_ID_ENCRYPTION_PURPOSE=$AWS_CRYPTO_CONTEXT_TAX_ID_ENCRYPTION_PURPOSE' >> $BASH_ENV
             echo 'export AWS_CRYPTO_CONTEXT_TAX_ID_HASHING_PURPOSE=$AWS_CRYPTO_CONTEXT_TAX_ID_HASHING_PURPOSE' >> $BASH_ENV
             echo 'export AWS_CRYPTO_TAX_ID_ENCRYPTION_KEY=$AWS_CRYPTO_TAX_ID_ENCRYPTION_KEY_DEV' >> $BASH_ENV
             echo 'export AWS_CRYPTO_TAX_ID_HASHING_KEY=$AWS_CRYPTO_TAX_ID_HASHING_KEY_DEV' >> $BASH_ENV
-            echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV' >> $BASH_ENV
+            echo 'export AWS_SECRET_ACCESS_KEY=local' >> $BASH_ENV
             echo 'export CHECK_DEAD_LINKS=$CHECK_DEAD_LINKS_DEV' >> $BASH_ENV
             echo 'export COGNITO_IDENTITY_POOL_ID=$COGNITO_IDENTITY_POOL_ID_DEV' >> $BASH_ENV
             echo 'export COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID_DEV' >> $BASH_ENV
@@ -329,9 +381,12 @@ commands:
       - run:
           name: Set Staging Environment Variables
           command: |
+            echo 'export VPC_ID=$VPC_ID_AWS_STAGING' >> $BASH_ENV
+            echo 'export SUBNET_ID_01=$SUBNET_ID_01_AWS_STAGING' >> $BASH_ENV
+            echo 'export SUBNET_ID_02=$SUBNET_ID_02_AWS_STAGING' >> $BASH_ENV
+            echo 'export SG_ID=$SG_ID_AWS_STAGING' >> $BASH_ENV
             echo 'export API_BASE_URL=$API_BASE_URL_AWS_STAGING' >> $BASH_ENV
             echo 'export AUTH_DOMAIN=$COGNITO_AUTH_DOMAIN_STAGING' >> $BASH_ENV
-            echo 'export BIZNJ_SLS_DEPLOYMENT_BUCKET_NAME=$BIZNJ_SLS_DEPLOYMENT_BUCKET_NAME_STAGING' >> $BASH_ENV
             echo 'export BUSINESS_NAME_BASE_URL=$BUSINESS_NAME_BASE_URL_STAGING' >> $BASH_ENV
             echo 'export COGNITO_IDENTITY_POOL_ID=$COGNITO_IDENTITY_POOL_ID_STAGING' >> $BASH_ENV
             echo 'export COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID_STAGING' >> $BASH_ENV
@@ -350,7 +405,6 @@ commands:
             echo 'export MYNJ_SERVICE_URL=$MYNJ_SERVICE_URL_STAGING' >> $BASH_ENV
             echo 'export NEXT_PUBLIC_WEB_BASE_URL=$WEB_BASE_URL_STAGING' >> $BASH_ENV
             echo 'export REDIRECT_URL=$REDIRECT_URL_STAGING' >> $BASH_ENV
-            echo 'export SERVERLESS_ACCESS_KEY=$SERVERLESS_ACCESS_KEY_STAGING' >> $BASH_ENV
             echo 'export XRAY_REGISTRATION_STATUS_BASE_URL=$XRAY_REGISTRATION_STATUS_BASE_URL_STAGING' >> $BASH_ENV
 
             echo 'export AB_TESTING_EXPERIENCE_B_PERCENTAGE=$AB_TESTING_EXPERIENCE_B_PERCENTAGE_STAGING' >> $BASH_ENV
@@ -403,9 +457,12 @@ commands:
       - run:
           name: Set Production Environment Variables
           command: |
+            echo 'export VPC_ID=$VPC_ID_AWS_PROD' >> $BASH_ENV
+            echo 'export SUBNET_ID_01=$SUBNET_ID_01_AWS_PROD' >> $BASH_ENV
+            echo 'export SUBNET_ID_02=$SUBNET_ID_02_AWS_PROD' >> $BASH_ENV
+            echo 'export SG_ID=$SG_ID_AWS_PROD' >> $BASH_ENV
             echo 'export API_BASE_URL=$API_BASE_URL_AWS_PROD' >> $BASH_ENV
             echo 'export AUTH_DOMAIN=$COGNITO_AUTH_DOMAIN_PROD' >> $BASH_ENV
-            echo 'export BIZNJ_SLS_DEPLOYMENT_BUCKET_NAME=$BIZNJ_SLS_DEPLOYMENT_BUCKET_NAME_PROD' >> $BASH_ENV
             echo 'export BUSINESS_NAME_BASE_URL=$BUSINESS_NAME_BASE_URL_PROD' >> $BASH_ENV
             echo 'export COGNITO_IDENTITY_POOL_ID=$COGNITO_IDENTITY_POOL_ID_PROD' >> $BASH_ENV
             echo 'export COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID_PROD' >> $BASH_ENV
@@ -423,7 +480,6 @@ commands:
             echo 'export MYNJ_SERVICE_URL=$MYNJ_SERVICE_URL_PROD' >> $BASH_ENV
             echo 'export NEXT_PUBLIC_WEB_BASE_URL=$WEB_BASE_URL_PROD' >> $BASH_ENV
             echo 'export REDIRECT_URL=$REDIRECT_URL_PROD' >> $BASH_ENV
-            echo 'export SERVERLESS_ACCESS_KEY=$SERVERLESS_ACCESS_KEY_PROD' >> $BASH_ENV
             echo 'export XRAY_REGISTRATION_STATUS_BASE_URL=$XRAY_REGISTRATION_STATUS_BASE_URL_PROD' >> $BASH_ENV
 
             echo 'export FEATURE_BUSINESS_FLP=$FEATURE_BUSINESS_FLP_PROD' >> $BASH_ENV
@@ -479,8 +535,10 @@ commands:
       - run:
           name: Set Content Environment Variables
           command: |
-            echo 'export BIZNJ_SLS_DEPLOYMENT_BUCKET_NAME=$BIZNJ_SLS_DEPLOYMENT_BUCKET_NAME_CONTENT' >> $BASH_ENV
-            echo 'export SERVERLESS_ACCESS_KEY=$SERVERLESS_ACCESS_KEY_CONTENT' >> $BASH_ENV
+            echo 'export VPC_ID=$VPC_ID_AWS_DEV' >> $BASH_ENV
+            echo 'export SUBNET_ID_01=$SUBNET_ID_01_AWS_DEV' >> $BASH_ENV
+            echo 'export SUBNET_ID_02=$SUBNET_ID_02_AWS_DEV' >> $BASH_ENV
+            echo 'export SG_ID=$SG_ID_AWS_DEV' >> $BASH_ENV
             echo 'export API_BASE_URL=$API_BASE_URL_AWS_CONTENT' >> $BASH_ENV
             echo 'export AUTH_DOMAIN=$COGNITO_AUTH_DOMAIN_CONTENT' >> $BASH_ENV
             echo 'export MYNJ_ROLE_NAME=$MYNJ_ROLE_NAME_CONTENT' >> $BASH_ENV
@@ -500,6 +558,10 @@ commands:
       - run:
           name: Set Testing Environment Variables
           command: |
+            echo 'export VPC_ID=$VPC_ID_AWS_DEV' >> $BASH_ENV
+            echo 'export SUBNET_ID_01=$SUBNET_ID_01_AWS_DEV' >> $BASH_ENV
+            echo 'export SUBNET_ID_02=$SUBNET_ID_02_AWS_DEV' >> $BASH_ENV
+            echo 'export SG_ID=$SG_ID_AWS_DEV' >> $BASH_ENV
             echo 'export API_BASE_URL=$API_BASE_URL_AWS_TESTING' >> $BASH_ENV
             echo 'export AUTH_DOMAIN=$COGNITO_AUTH_DOMAIN_TESTING' >> $BASH_ENV
             echo 'export AWS_CRYPTO_CONTEXT_TAX_ID_HASHING_PURPOSE=$AWS_CRYPTO_CONTEXT_TAX_ID_HASHING_PURPOSE' >> $BASH_ENV
@@ -507,7 +569,6 @@ commands:
             echo 'export AWS_CRYPTO_TAX_ID_HASHING_KEY=$AWS_CRYPTO_TAX_ID_HASHING_KEY_TESTING' >> $BASH_ENV
             echo 'export BASIC_AUTH_AGENCY_PASSWORD=$BASIC_AUTH_AGENCY_PASSWORD_TESTING' >> $BASH_ENV
             echo 'export BASIC_AUTH_AGENCY_USERNAME=$BASIC_AUTH_AGENCY_USERNAME_TESTING' >> $BASH_ENV
-            echo 'export BIZNJ_SLS_DEPLOYMENT_BUCKET_NAME=$BIZNJ_SLS_DEPLOYMENT_BUCKET_NAME_TESTING' >> $BASH_ENV
             echo 'export COGNITO_IDENTITY_POOL_ID=$COGNITO_IDENTITY_POOL_ID_ACCESSIBILITY_TESTING' >> $BASH_ENV
             echo 'export COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID_ACCESSIBILITY_TESTING' >> $BASH_ENV
             echo 'export COGNITO_WEB_CLIENT_ID=$COGNITO_WEB_CLIENT_ID_ACCESSIBILITY_TESTING' >> $BASH_ENV
@@ -515,7 +576,6 @@ commands:
             echo 'export MYNJ_SERVICE_TOKEN=$MYNJ_SERVICE_TOKEN_TESTING' >> $BASH_ENV
             echo 'export NEXT_PUBLIC_WEB_BASE_URL=$WEB_BASE_URL_TESTING' >> $BASH_ENV
             echo 'export REDIRECT_URL=$REDIRECT_URL_ACCESSIBILITY_TESTING' >> $BASH_ENV
-            echo 'export SERVERLESS_ACCESS_KEY=$SERVERLESS_ACCESS_KEY_TESTING' >> $BASH_ENV
 
   deploy-setup:
     steps:
@@ -523,7 +583,7 @@ commands:
       - setup_remote_docker:
           version: edge
           docker_layer_caching: true
-      - deploy-serverless
+      - deploy-cdk
 
   deploy-content-env:
     steps:
@@ -827,12 +887,15 @@ jobs:
           at: .
       - configure-and-build
       - install-dynamodb
+      - start-dynamodb
+      - wait-for-dynamodb
+      - initialize-dynamodb-tables
       - perform-integration-tests:
           enable-dashboard: << parameters.enable-dashboard >>
           suite: << parameters.suite >>
           browser: << parameters.browser >>
     environment:
-      CYPRESS_API_BASE_URL: http://localhost:5002/local
+      CYPRESS_API_BASE_URL: http://localhost:5002
 
   smoke-tests:
     parameters:
